name: GitHub Pages action
  uses: peaceiris/actions-gh-pages@v3.7.3

on: [push, pull_request]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn

      - name: Generate
        run: yarn run generate
        env:
          CD: true
          CTF_BLOG_POST_TYPE_ID: ${{secrets.CTF_BLOG_POST_TYPE_ID}}
          CTF_SPACE_ID: ${{secrets.CTF_SPACE_ID}}
          CTF_PERSON_ID: ${{secrets.CTF_PERSON_ID}}
          CTF_CDA_ACCESS_TOKEN: ${{secrets.CTF_CDA_ACCESS_TOKEN}}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
